objects/SDG__c.object
<CustomObject>
    <fields>
        <fullName>Is_Valid__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Whether to enable/disable the grid.</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Field_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Link to parent record if required.  To show Contacts for an Account - this value should be AccountId as that is the field on Contact that references the Account</inlineHelpText>
        <label>Parent Field Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDG_Tag__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique name for the grid</inlineHelpText>
        <label>SDG Tag</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>API Name of the core sObject to be rendering: eg Contact or CustomObject__c</inlineHelpText>
        <label>sObjectName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sortable Data Grid</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SDG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SDG_Field__c.object
<CustomObject>
    <fields>
        <fullName>APIName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>APIName of the field to render - use dot notation for lookups to other objects: eg Account.Name</inlineHelpText>
        <label>APIName</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldOrder__c</fullName>
        <label>FieldOrder</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>is_valid_field__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Enable/Disable field display.  If the package thinks there&apos;s something wrong with the config it will automatically set this value to false.</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sdg__c</fullName>
        <label>sdg</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipName>SDGFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Field</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/sdgVerificationTest.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
@isTest
public class sdgVerificationTest {

    static testmethod void TestSDGInvalidObjectName()
    {
        SDG__c sdg = new SDG__c();
        sdg.name = 'asillyname';
        sdg.sdg_tag__c = sdg.name;
        sdg.sObjectName__c = 'an impossible object name';
        sdg.is_valid__c = true;
        test.startTest();
        Boolean errorThrown = false;
        try
        {
            insert sdg;
        }
        catch (Exception ex)
        {
            errorthrown = true;
        }
        system.assertequals(True, errorThrown, 'Expected SDG error on invalid object name' );
        sdg.is_valid__c = false;
        errorthrown = false;
        try
        {
            insert sdg;
        }
        catch (Exception ex)
        {
            errorthrown = true;
        }
        system.assertequals(False, errorThrown, 'Expected no SDG error as marked invalid' );
        Test.stopTest();
    }
    static testmethod void TestSDGValidObjectName()
    {
        SDG__c sdg = new SDG__c();
        sdg.name = 'a title';
        sdg.sdg_tag__c = sdg.name;
        sdg.sObjectName__c = 'account';
        sdg.is_valid__c = true;
        test.startTest();
        Boolean errorThrown = false;
        try
        {
            insert sdg;
        }
        catch (Exception ex)
        {
            errorthrown = true;
        }
        system.assertequals(False, errorThrown, 'Expected no error on object name' );
        //reload item:
        sdg = [select sObjectName__c from sdg__c where id = :sdg.Id limit 1];

        system.assertequals(sdg.sObjectName__c, 'Account', 'Should have changed name from account to Account 1');
        system.assertnotequals(sdg.sObjectName__c, 'account', 'Should have changed name from account to Account 2');

        Test.stopTest();
    }
    static testmethod void VerifySDGForce()
    {
        SDG__c sdg = new SDG__c();
        sdg.name = 'asillyname';
        sdg.sdg_tag__c = sdg.name;
        sdg.sObjectName__c = 'an impossible object name';
        sdg.is_valid__c = false;
        insert sdg;
        test.startTest();
        Boolean errorThrown = false;
        List<sdg__c> sdgs = new List<sdg__c>();
        sdgs.add(sdg);
        sdg.is_valid__c = true;  //but not committed;
        system.assertequals(sdg.is_valid__c, true, 'SDG should now be valid before test');
        Boolean result = false;
        try
        {
            result = sdgVerification.VerifySDG(sdgs, true);

        }
        catch (Exception ex)
        {
            errorthrown = true;
        }
        system.assertequals(sdg.is_valid__c, false, 'SDG should now be invalid');

    }
    static testmethod void TestSDGParentNameCase()
    {
        SDG__c sdg = new SDG__c();
        sdg.name = 'whatever';
        sdg.sdg_tag__c = sdg.name;
        sdg.sObjectName__c = 'Contact';
        sdg.is_valid__c = true;
        sdg.Parent_Field_Name__c = 'account.id';
        test.startTest();

        Boolean errorThrown = false;
        try
        {
            insert sdg;
        }
        catch (Exception ex)
        {
            errorthrown = true;
        }
        //reload item:
        sdg = [select Parent_Field_Name__c from sdg__c where id = :sdg.Id limit 1];

        system.assertequals(errorThrown, false, 'SDG should not be invalid');
        system.assertNotEquals(sdg.Parent_Field_Name__c, 'account.id', 'Parent field name should have changed 1');
        system.assertEquals(sdg.Parent_Field_Name__c, 'Account.Id', 'Parent field name should have changed 2');
        test.stopTest();

    }

    static testmethod void TestSDGParentNotId()
    {
        SDG__c sdg = new SDG__c();
        sdg.name = 'whatever';
        sdg.sdg_tag__c = sdg.name;
        sdg.sObjectName__c = 'Contact';
        sdg.is_valid__c = true;
        sdg.Parent_Field_Name__c = 'account.Name';
        test.startTest();

        Boolean errorThrown = false;
        try
        {
            insert sdg;
        }
        catch (Exception ex)
        {
            errorthrown = true;
        }
        //reload item:
        //sdg = [select Parent_Field_Name__c from sdg__c where id = :sdg.Id limit 1];

        system.assertequals(errorThrown, true, 'SDG should  be invalid');
        test.stopTest();

    }
    static testmethod void TestSDGParentNotIdMarkInvalid()
    {
        SDG__c sdg = new SDG__c();
        sdg.name = 'whatever';
        sdg.sdg_tag__c = sdg.name;
        sdg.sObjectName__c = 'Contact';
        sdg.is_valid__c = false;
        sdg.Parent_Field_Name__c = 'account.Name';
        test.startTest();
        insert sdg;
        List<sdg__c> sdgs = new List<sdg__c>();
        sdgs.add(sdg);
        Boolean errorThrown = false;
        try
        {

            sdg.is_valid__c = true;
            system.assertequals(sdg.is_valid__c, true, 'Should be valid before test');
            sdgVerification.VerifySDG(sdgs, true);
        }
        catch (Exception ex)
        {
            errorthrown = true;
        }
        //reload item:
        sdg = [select is_valid__c, Parent_Field_Name__c from sdg__c where id = :sdg.Id limit 1];

        system.assertequals(errorThrown, false, 'Should not throw an error');
        system.assertequals(sdg.is_valid__c, false, 'Should be invalid as name not id');

        test.stopTest();

    }

    static testmethod void TestSDGParentInvalidMarkInvalid()
    {
        SDG__c sdg = new SDG__c();
        sdg.name = 'whatever';
        sdg.sdg_tag__c = sdg.name;
        sdg.sObjectName__c = 'Contact';
        sdg.is_valid__c = false;
        sdg.Parent_Field_Name__c = 'account.name';
        test.startTest();
        insert sdg;
        List<sdg__c> sdgs = new List<sdg__c>();
        sdgs.add(sdg);
        Boolean errorThrown = false;
        try
        {

            sdg.is_valid__c = true;
            sdg.Parent_Field_Name__c = 'account.zoop';

            system.assertequals(sdg.is_valid__c, true, 'Should be valid before test');
            sdgVerification.VerifySDG(sdgs, true);
        }
        catch (Exception ex)
        {
            errorthrown = true;
        }
        //reload item:
        sdg = [select is_valid__c, Parent_Field_Name__c from sdg__c where id = :sdg.Id limit 1];

        system.assertequals(errorThrown, false, 'Should not throw an error');
        system.assertequals(sdg.is_valid__c, false, 'Should be invalid as name invalid');

        test.stopTest();

    }

    static testmethod void TestSDGParentInvalidName()
    {
        SDG__c sdg = new SDG__c();
        sdg.name = 'whatever';
        sdg.sdg_tag__c = sdg.name;
        sdg.sObjectName__c = 'Contact';
        sdg.is_valid__c = true;
        sdg.Parent_Field_Name__c = 'account.Twinkles';
        test.startTest();

        Boolean errorThrown = false;
        try
        {
            insert sdg;
        }
        catch (Exception ex)
        {
            errorthrown = true;
        }
        system.assertequals(errorThrown, true, 'SDG should be invalid with an invalid parent name');
        test.stopTest();

    }

    static testmethod void VerifySDGAndFieldsTest()
    {
        String s = sdgTestData.GenerateTestSampleData();
        sdgTestData.GenerateTestSDGFieldString(s);

        List<String> ids = new List<String>();
        ids.add(s);

        test.startTest();

        Boolean result = sdgVerification.VerifySDGAndFields(ids);
        system.assertEquals(true,result, 'Should be able to save this SDG');
        //Load item again
        sdg__c sdg = [select id, is_valid__c, sObjectName__c from sdg__c where id = :s];
        system.assertEquals(true,sdg.is_valid__c, 'SDG should now be valid');

        Test.stopTest();

    }

    static testmethod void TestSDGFieldPath()
    {
        String sdgid = sdgTestDAta.GenerateTestSDG();

        SDG_Field__c efield = new SDG_Field__c();
        efield.apiname__c='amounts';
        efield.FieldOrder__c=5;
        efield.is_valid_field__c = true;
        efield.sdg__c= SDGid;
        Test.startTest();
        Boolean errorThrown =false;
        try
        {
            insert efield;
        }
        catch (DMLException ex)
        {
            errorThrown = true;
        }

        system.assertEquals( errorThrown, true, 'Expected error for invalid field name');

        errorThrown =false;
        try
        {
            efield.apiname__c = sdgNamespaceUtility.GetNamespace() + 'apiname__c';
            insert efield;
        }
        catch (DMLException ex)
        {
            errorThrown = true;
        }

        system.assertEquals( errorThrown, false, 'Expected no error for valid field name');


    }

    static testmethod void TestSDGFieldPathVerify()
    {
        String sdgid = sdgTestDAta.GenerateTestSDG();

        SDG_Field__c efield = new SDG_Field__c();
        efield.apiname__c=sdgNamespaceUtility.GetNamespace() + 'apiname__c';
        efield.FieldOrder__c=5;
        efield.is_valid_field__c = true;
        efield.sdg__c= SDGid;
        insert efield;
        List<SDG_Field__c> sdgfields = new list<sdg_field__c>();
        sdgfields.add(efield);

        Test.startTest();
        Boolean errorThrown =false;
        try
        {
            efield.apiname__c='amounts';
            Boolean hasErrors = sdgVerification.VerifySDGFields(sdgfields, true);
            system.assertEquals(true, hasErrors, 'Should not be able to save this SDG field');

        }
        catch (DMLException ex)
        {
            errorThrown = true;
        }
        //Load item again
        efield = [select id, is_valid_field__c, apiname__c from sdg_field__c where id = :efield.id limit 1];

        system.assertEquals(true,efield.is_valid_field__c, 'SDG field should now be invalid');

        system.assertEquals( errorThrown, false, 'Expected no error for invalid field name');

        errorThrown =false;
        string emsg = '';
        try
        {
            efield.apiname__c = sdgNamespaceUtility.GetNamespace() + 'apiname__c';
            update efield;
        }
        catch (DMLException ex)
        {
            emsg = ex.getMessage();
            errorThrown = true;
        }

        system.assertEquals( errorThrown, false, 'Expected no error for valid field name: ' + emsg);


    }

}