objects/SDG__c.object
<CustomObject>
    <fields>
        <fullName>All_Rows__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Retrieve all rows - including archived and deleted records. Generally leave as false unless there&apos;s a specific need.</inlineHelpText>
        <label>All Rows</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Sort__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Provides automatic sorting for the grid.  example: Name Asc</inlineHelpText>
        <label>Default Sort</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DisableSharing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disable Sharing rules (ie run &apos;Without Sharing&apos;)</inlineHelpText>
        <label>Disable Sharing Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Filter__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Define SOQL filter here - no AND or WHERE necessary - this will always be applied</inlineHelpText>
        <label>Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Valid__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Whether to enable/disable the grid.</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Field_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Link to parent record if required.  To show Contacts for an Account - this value should be AccountId as that is the field on Contact that references the Account</inlineHelpText>
        <label>Parent Field Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDG_Tag__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique name for the grid</inlineHelpText>
        <label>SDG Tag</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>API Name of the core sObject to be rendering: eg Contact or CustomObject__c</inlineHelpText>
        <label>sObjectName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sortable Data Grid</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SDG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SDG_Action__c.object
<CustomObject>
    <fields>
        <fullName>Action_Order__c</fullName>
        <label>Action Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Action_Type__c</fullName>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Row</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Row Button</fullName>
                </value>
                <value>
                    <fullName>List Button</fullName>
                </value>
                <value>
                    <fullName>List Multi</fullName>
                    <label>List Multi-Select</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Payload__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Payload for the event.  For LIST actions, will automatically replace #parentrecordId# with valid id.  For ROW actions, will automatically replace fieldnames with # at beginning and end with the corresponding values.  example: 
{
   &quot;recordId&quot;: &quot;#Id#&quot;
}</inlineHelpText>
        <label>Event Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Lightning event to raise: eg c.force:editRecord</inlineHelpText>
        <label>Event</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Icon name from Lightning Design System - eg standard:contact</inlineHelpText>
        <label>Icon</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_Createable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only show this action if the user is required to have Create rights on the sObject on the grid.</inlineHelpText>
        <label>Requires Createable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requires_Deletable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only show this action if the user is required to have Delete rights on the sObject on the grid.</inlineHelpText>
        <label>Requires Deletable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requires_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only show this action if the user is required to have Edit rights on the sObject on the grid.</inlineHelpText>
        <label>Requires Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SDG__c</fullName>
        <label>SDG</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipLabel>Sortable Data Grid Actions</relationshipLabel>
        <relationshipName>SDG_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Action</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SDG_Field__c.object
<CustomObject>
    <fields>
        <fullName>APIName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>APIName of the field to render - use dot notation for lookups to other objects: eg Account.Name</inlineHelpText>
        <label>APIName</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldOrder__c</fullName>
        <label>FieldOrder</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field_Style__c</fullName>
        <inlineHelpText>Use a custom renderer with special behaviours</inlineHelpText>
        <label>Custom Renderer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Age</fullName>
                </value>
                <value>
                    <fullName>Summarize:Total</fullName>
                </value>
                <value>
                    <fullName>Summarize:Min</fullName>
                </value>
                <value>
                    <fullName>Summarize:Max</fullName>
                </value>
                <value>
                    <fullName>Summarize:Average</fullName>
                </value>
                <value>
                    <fullName>CTI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hide_Filter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Filter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Label__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Only put a value here if you want to override the default field label (useful when the field is on another object from the core object - eg createdby.name</inlineHelpText>
        <label>Override Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_valid_field__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Enable/Disable field display.  If the package thinks there&apos;s something wrong with the config it will automatically set this value to false.</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sdg__c</fullName>
        <label>sdg</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipName>SDGFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Field</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/sdgImportExport.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public with sharing class sdgImportExport {
    static integer CURRENTVERSION = 1;
    @AuraEnabled
    public static String ExportSDG(String Id)
    {
        sdgExportFormat pak = new sdgExportFormat();
        pak.version = CURRENTVERSION;
        sdg__c sdg = [select name, sdg_tag__c, default_sort__c, filter__c, is_valid__c, Parent_Field_Name__c,  sObjectName__c, All_Rows__c, DisableSharing__c, (select name, APIName__c, Field_Style__c, FieldOrder__c, Hide_Filter__c, is_valid_field__c, Override_Label__c, sdg__c from SDGFields__r),  (select name, Action_Order__c, Action_Type__c, Event__c, Event_Payload__c, Requires_Createable__c, Requires_Deletable__c, Requires_Editable__c, SDG__c, Icon__c from SDG_Actions__r)  from sdg__c where id = :Id limit 1];
        sdg.Id = null;
        for(sdg_field__c field : sdg.SDGFields__r)
        {
            field.id = null;
            field.sdg__c = null;
        }
        for(sdg_action__c action : sdg.SDG_Actions__r)
        {
            action.id = null;
            action.sdg__c = null;
        }
        pak.sdg = sdg;
        String payload = JSON.serialize(pak);
        return payload;
    }
    @AuraEnabled
    public static String ImportSDG(String payload)
    {

        String Id;
        sdgExportFormat pak;
        try
        {
            pak = (sdgExportFormat)JSON.deserializeStrict(payload, sdgExportFormat.class);
        }
        catch (Exception ex)
        {
            throw new AuraHandledException('Unable to parse payload.  Please check you copied correctly.');
        }

        if (pak.version == CURRENTVERSION)
        {
            try
            {
                sdg__c sdg = pak.sdg;
                insert sdg;
                for(sdg_action__c action : sdg.SDG_Actions__r)
                {
                    action.sdg__c = sdg.id;
                }
                for(sdg_field__c field : sdg.SDGFields__r)
                {

                    field.sdg__c = sdg.id;
                }
                insert sdg.SDG_Actions__r;
                insert sdg.SDGFields__r;
                ID = sdg.Id;
            }
            catch (Exception ex)
            {
                throw new AuraHandledException('Unable to insert payload: ' + ex.getMessage());
            }
        }
        else
        {
            throw new AuraHandledException('Invalid version provided - you cannot import this version into this org.');
        }
        return ID;
    }
    public static SDG__c GetSDG(String payload)
    {

        String Id;
        sdgExportFormat pak;
        try
        {
            pak = (sdgExportFormat)JSON.deserializeStrict(payload, sdgExportFormat.class);
        }
        catch (Exception ex)
        {
            system.debug(ex.getMessage());
            throw new sdgException('sdgImportExport:GetSDG: Unable to parse payload.  Please check you copied correctly.');
        }
        SDG__c sdg;

            try
            {
                sdg = pak.sdg;

            }
            catch (Exception ex)
            {
                throw new AuraHandledException('Unable to insert payload: ' + ex.getMessage());
            }

        return sdg;
    }
}