objects/SDG__c.object
<CustomObject>
    <fields>
        <fullName>sObjectName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>API Name of the core sObject to be rendering: eg Contact or CustomObject__c</inlineHelpText>
        <label>sObjectName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sortable Data Grid</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SDG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SDG_Action__c.object
<CustomObject>
    <fields>
        <fullName>SDG__c</fullName>
        <label>SDG</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipLabel>Sortable Data Grid Actions</relationshipLabel>
        <relationshipName>SDG_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Action</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SDG_Field__c.object
<CustomObject>
    <fields>
        <fullName>sdg__c</fullName>
        <label>sdg</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipName>SDGFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Field</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SDGDefaults__mdt.object
<CustomObject>
    <fields>
        <fullName>Definition__c</fullName>
        <label>Definition</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <label>SDGDefault</label>
    <pluralLabel>SDGDefaults</pluralLabel>
</CustomObject>

classes/sdgDataProviderMetadata.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
global with sharing class sdgDataProviderMetadata implements sdgIDataProvider {
    global static Boolean isUserSelectable()
    {
        return false;
    }

    global static SDGResult getData(SDG CoreSDG, SDGRequest request)
    {

        SDGResult result =  sdgQueryEngine.getSDGResultRaw(CoreSDG, request);
        return result;
    }


    global SDG LoadSDG(String SDGTag, String ParentRecordId)
    {
        SDG CoreSDG = null;
        try
        {

            SDGDefaults__mdt md = [SELECT Id, Definition__c FROM SDGDefaults__mdt where developername = :SDGTag limit 1];
     
            String definition = md.definition__c.replace('$namespace$', sdgNamespaceUtility.GetNamespace());
     
            SDG__c e =  sdgImportExport.getSDG(definition);

            CoreSDG = sdgMapper.Convert(e, e.sdgfields__r, sdgSecurity.PermittedActions(e.sObjectName__c, e.sdg_actions__r), false);

            //now put the fields and action ids on - as they won't be in the pak payload
            integer iCounter = 1;
            coresdg.SDGFields.sort();
            coresdg.SDGActions.sort();
            
            for (SDGField field: coresdg.SDGFields)
            {
                field.id = string.valueOf(icounter);
                icounter++;
            }
            for (sdgAction action: coresdg.SDGActions)
            {
                action.id = string.valueOf(icounter);
                icounter++;
            }


            system.debug('sdgDataProviderMetadata:LoadSDG: ' + SDGTag + ' ' + JSON.serialize(CoreSDG) );
        }
        catch (Exception ex)
        {
            throw new sdgException('sdgDataProviderMetadata:LoadSDG: ' + SDGTag + ' : ' + ex.getMessage());
        }
        return coreSDG;
    }


}