objects/SDG__c.object
<CustomObject>
    <fields>
        <fullName>Is_Valid__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Whether to enable/disable the grid.</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Field_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Link to parent record if required.  To show Contacts for an Account - this value should be AccountId as that is the field on Contact that references the Account</inlineHelpText>
        <label>Parent Field Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDG_Tag__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique name for the grid</inlineHelpText>
        <label>SDG Tag</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>API Name of the core sObject to be rendering: eg Contact or CustomObject__c</inlineHelpText>
        <label>sObjectName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sortable Data Grid</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SDG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SDG_Action__c.object
<CustomObject>
    <fields>
        <fullName>Action_Order__c</fullName>
        <label>Action Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Action_Type__c</fullName>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Row</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Row Button</fullName>
                </value>
                <value>
                    <fullName>List Button</fullName>
                </value>
                <value>
                    <fullName>List Multi</fullName>
                    <label>List Multi-Select</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Payload__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Payload for the event.  For LIST actions, will automatically replace #parentrecordId# with valid id.  For ROW actions, will automatically replace fieldnames with # at beginning and end with the corresponding values.  example: 
{
   &quot;recordId&quot;: &quot;#Id#&quot;
}</inlineHelpText>
        <label>Event Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Lightning event to raise: eg c.force:editRecord</inlineHelpText>
        <label>Event</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_Createable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only show this action if the user is required to have Create rights on the sObject on the grid.</inlineHelpText>
        <label>Requires Createable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requires_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only show this action if the user is required to have Edit rights on the sObject on the grid.</inlineHelpText>
        <label>Requires Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SDG__c</fullName>
        <label>SDG</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipLabel>Sortable Data Grid Actions</relationshipLabel>
        <relationshipName>SDG_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Action</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SDG_Field__c.object
<CustomObject>
    <fields>
        <fullName>APIName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>APIName of the field to render - use dot notation for lookups to other objects: eg Account.Name</inlineHelpText>
        <label>APIName</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldOrder__c</fullName>
        <label>FieldOrder</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field_Style__c</fullName>
        <inlineHelpText>Use a custom renderer with special behaviours</inlineHelpText>
        <label>Custom Renderer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Age</fullName>
                </value>
                <value>
                    <fullName>Summarize:Total</fullName>
                </value>
                <value>
                    <fullName>Summarize:Min</fullName>
                </value>
                <value>
                    <fullName>Summarize:Max</fullName>
                </value>
                <value>
                    <fullName>Summarize:Average</fullName>
                </value>
                <value>
                    <fullName>CTI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>is_valid_field__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Enable/Disable field display.  If the package thinks there&apos;s something wrong with the config it will automatically set this value to false.</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sdg__c</fullName>
        <label>sdg</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipName>SDGFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Field</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/sdgTestData.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
@isTest
public class sdgTestData {
    public static String TestSDGName = 'TestSDG';
    public static String TestSampleSDGName = 'SampleDataSDG';

    private  static string GenerateTestData(String SDGName)
    {
        //self referential - sdg showing sdg fields...
        string sdgid = GenerateCoreSDG(SDGName);
        List<SDG_Field__c> fields = new List<SDG_Field__c>();
        GenerateTestSDGFieldString(sdgid, 'name', 1);
        GenerateTestSDGFieldString(sdgid, sdgNamespaceUtility.GetNamespace() + 'apiname__c',2);

        return sdgid;
    }
    public static string GenerateCoreSDG(String SDGName)
    {
        SDG__c a = new SDG__c(Name=SDGName, sdg_tag__c = SDGName, is_valid__c=true, sobjectname__c=sdgNamespaceUtility.GetNamespace() + 'sdg_field__c', parent_field_name__c = sdgNamespaceUtility.GetNamespace() + 'sdg__r.id');
        insert a;
        system.debug('CreatedSDG: id: ' + a.id + ' - Name: ' + SDGName);
        return a.id;
    }
    public static string GenerateTestSampleData()
    {
        return GenerateTestData(TestSampleSDGName);
    }
    public static String GenerateTestSDG()
    {
        //Create a custom SDG:
        String id = GenerateTestData(TestSDGName);
        GenerateAction(id);

        return Id;

    }
    public static string GenerateTestSDGFieldStringName(String SDGID)
    {
        return GenerateTestSDGFieldString(sdgid, 'Name',1);
    }

    public static string GenerateTestSDGFieldString(String SDGID)
    {
        return GenerateTestSDGFieldString(sdgid, sdgNamespaceUtility.GetNamespace() + 'APIname__c',1);
    }

    public static string GenerateTestSDGFieldString(String SDGID, String fieldName, integer fieldorder)
    {
        //String Field
        SDG_Field__c field = new SDG_Field__c( apiname__c=fieldName, fieldOrder__c = fieldorder, sdg__c=sdgid, is_valid_field__c=true );
        insert field;
        return field.id;
    }

    /*public static string GenerateTestSDGFieldTraverseString(String SDGID)
    {
        //String Field
        SDG_Field__c field = new SDG_Field__c( apiname__c=sdgNamespaceUtility.GetNamespace() + 'sdg__r.name', fieldOrder__c = 2, sdg__c=sdgid, is_valid_field__c=true );
        insert field;
        return field.id;
    }
*/
    public static string GenerateTestSDGFieldNumber(String SDGID)
    {
        //String Field
        SDG_Field__c field = new SDG_Field__c( apiname__c=sdgNamespaceUtility.GetNamespace() + 'fieldorder__c', fieldOrder__c = 3, sdg__c=sdgid, is_valid_field__c=true );
        insert field;
        return field.id;

    }

    public static string GenerateTestSDGFieldDate(String SDGID)
    {
        //Date
        SDG_Field__c field = new SDG_Field__c( apiname__c='createddate', fieldOrder__c = 4, sdg__c=sdgid, is_valid_field__c=true );
        insert field;
        return field.id;

    }
    public static string GenerateTestSDGFieldDateTime(String SDGID)
    {
        //Date
        SDG_Field__c field = new SDG_Field__c( apiname__c='lastmodifieddate', fieldOrder__c = 5, sdg__c=sdgid, is_valid_field__c=true );
        insert field;
        return field.id;
    }
    public static string GenerateTestSDGFieldBoolean(String SDGID)
    {
        SDG_Field__c field = new SDG_Field__c( apiname__c=sdgNamespaceUtility.GetNamespace() + 'is_valid_field__c', fieldOrder__c = 6, sdg__c=sdgid, is_valid_field__c=true );
        insert field;
        return field.id;
    }
    public static string GenerateTestSDGFieldPicklist(String SDGID)
    {
        SDG_Field__c field = new SDG_Field__c( apiname__c=sdgNamespaceUtility.GetNamespace() + 'field_style__c', fieldOrder__c = 7, sdg__c=sdgid, is_valid_field__c=true );
        insert field;
        return field.id;
    }



    public static string GenerateAction(String sdgid)
    {
        SDG_Action__c act = new SDG_Action__c();
        act.requires_createable__c = true;
        act.Requires_Editable__c= true;
        act.Action_Type__c = 'List';
        act.event_payload__c = '{ dummy payload}';
        act.Action_Order__c=1;
        act.sdg__c = sdgid;
        act.Event__c='c.force:editRecord';
        insert act;
        return act.id;
    }
}