objects/SDG__c.object
<CustomObject>
    <fields>
        <fullName>Is_Valid__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Whether to enable/disable the grid.</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <label>Sortable Data Grid</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SDG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SDG_Field__c.object
<CustomObject>
    <fields>
        <fullName>APIName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>APIName of the field to render - use dot notation for lookups to other objects: eg Account.Name</inlineHelpText>
        <label>APIName</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldOrder__c</fullName>
        <label>FieldOrder</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>is_valid_field__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Enable/Disable field display.  If the package thinks there&apos;s something wrong with the config it will automatically set this value to false.</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sdg__c</fullName>
        <label>sdg</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipName>SDGFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Field</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/sdgControllerTest.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
@isTest
public with sharing class sdgControllerTest {
    /*
    static testMethod void GetSDGTest()
    {
        //Generate test data
        String testid = sdgTestData.GenerateTestSampleData();

        //Prep test catching values:
        Boolean errorThrown=false;
        String errorMsg = '';
        Test.startTest();

        //Test all params missing:
        try
        {
            SDG e = sdgLoaderFactory.LoadSDG('', '', '', '');

        }
        catch (SDGException ex)
        {
            errorThrown = true;
            errorMsg = ex.getMessage();
        }
        system.assertEquals(true, errorThrown, 'Expected an SDGException with no parameters');

        try
        {
            //sdgController SDGObj = new sdgController();
            SDG e = sdgLoaderFactory.LoadSDG(testid, 'Opportunities', '','');

        }
        catch (SDGException ex)
        {
            errorThrown = true;
            errorMsg = ex.getMessage();
        }
        system.assertEquals(true, errorThrown, 'Expected an SDGException with no fieldset');

        Test.stopTest();
    }



    static testMethod void TestCustomObjInitialLoad()
    {
        //Generate test data: an account and an opportunity:
        String testdata=sdgTestData.GenerateTestSampleData();

        STring sdgid = sdgTestData.GenerateTestSDG();
        //do not generate any fields to get an error

        Test.startTest();

        String results = sdgController.GetSDGInitialLoad(testdata, '', '', sdgTestData.TestSDGName);
        //json payload so parse
        SDGInitialLoad initial = (SDGInitialLoad)JSON.deserialize(results, SDGInitialLoad.class);
        system.assertEquals(true, initial.isError,'Expected error for SDG with no fields');
        Test.stopTest();
    }

    static testMethod void TestInvalidCustomObject()
    {
        //Generate test data: an account and an opportunity:
        String testdata=sdgTestData.GenerateTestSampleData();

        STring erlid = sdgTestData.GenerateTestSDG();
        //create invalid row:
        SDG_Field__c efield = new SDG_Field__c();
        efield.apiname__c='notavalidname';
        efield.FieldOrder__c=1;
        efield.sdg__c= erlid;
        efield.is_valid_field__c=true;

        //Prep test catching values:
        Boolean errorThrown=false;
        String errorMsg = '';
        Test.startTest();

        try
        {
            insert efield;

        }
        catch (DMLException ex)
        {
            errorThrown = true;
        }

        Test.stopTest();
        system.assertEquals(true, errorThrown, 'Expected invalid field to throw exception as invalid');

    }

    static testMethod void TestSDGInitialLoad()
    {
        //Generate test data: an account and an opportunity:
        String testdata=sdgTestData.GenerateTestSAmpleDAta();

        STring erlid = sdgTestData.GenerateTestSDG();
        sdgTestData.GenerateTestSDGFieldString(erlid);
        sdgTestData.GenerateTestSDGFieldDate(erlid);
        sdgTestData.GenerateTestSDGFieldBoolean(erlid);
        sdgTestData.GenerateTestSDGFieldPicklist(erlid);

        //Prep test catching values:
        Boolean errorThrown=false;
        String errorMsg = '';
        Test.startTest();

        //Test Happy Path
        String results = sdgController.GetSDGInitialLoad(testdata, sdgTestData.TestSDGName, '', '');
        //json payload so parse
        SDGInitialLoad initial = (SDGInitialLoad)JSON.deserialize(results, SDGInitialLoad.class);
        system.assertEquals(2, initial.results.filteredrowcount,'Expected rowcount=2 from load');
        system.assertEquals(2, initial.results.data.size(),'Expected data size=1 from load');
        system.assertEquals(false, initial.isError,'No error expected: initial');

        //Test UnHappy Path
        errorThrown=false;
        errorMsg = '';

        String results2 = sdgController.GetSDGInitialLoad(testdata, '', '', '');
        SDGInitialLoad initial2 = (SDGInitialLoad)JSON.deserialize(results2, SDGInitialLoad.class);
        system.assertEquals(true, initial2.isError, 'Expected handled error loading invalid Parent ID');
        system.assertEquals(false, initial.isError,'No error expected: initial2 ');
        //Test Unhappy Path

        errorThrown=false;
        errorMsg = '';
        String results3 = sdgController.GetSDGInitialLoad(testdata, '', '', 'invalid value');
        SDGInitialLoad initial3  = (SDGInitialLoad)JSON.deserialize(results3, SDGInitialLoad.class);
        system.assertEquals(true, initial3.isError, 'Expected handled error loading invalid SDG Tag');
        system.assertEquals(false, initial.isError,'No error expected: initial3 ');

        Test.stopTest();
    }

    static SDGResult GetResult(SDGRequest req)
    {
        String results = sdgController.getSDGResult(JSON.serialize(req));
        SDGResult result = (SDGResult)JSON.deserialize(results, SDGResult.class);
        return result;

    }

    static testMethod void TestSort()
    {
        //Generate test data:
        String testdata=sdgTestData.GenerateTestSampleData();

        STring erlid = sdgTestData.GenerateTestSDG();
        String stringfield = sdgTestData.GenerateTestSDGFieldString(erlid);
        String datefield = sdgTestData.GenerateTestSDGFieldDate(erlid);
        String booleanfield = sdgTestData.GenerateTestSDGFieldBoolean(erlid);
        String picklistfield = sdgTestData.GenerateTestSDGFieldPicklist(erlid);
        sdgTestData.GenerateTestSDGFieldTraverseString(erlid);

        Test.startTest();

        //Generate a request:
        SDGRequest req = new SDGRequest();
        req.SDGTag = sdgTestData.TestSDGName;
        req.ParentRecordID = testdata;
        req.pageid=1;
        req.pagesize=5;
        req.sortOrder='A';
        req.sortColumn=stringfield;

        //Now invoke normal list:
        SDGResult result = getresult(req);
        //Test this is sorted?
        system.assertEquals(2, result.filteredrowcount, 'expected two rows in sort results');
        SDG_field__c o = (SDG_field__c)result.data[0];
        system.assertEquals('Name', o.sortablegrid__APIName__c, 'Expected');
        system.assertEquals(false, result.isError,'Should not get error with valid sort value');

        //Test descending sort
        req.sortOrder='D';
        SDGResult result2 = getresult(req);

        //Test this is sorted?
        system.assertEquals(2, result.filteredrowcount, 'expected two rows in sort results');
        SDG_field__c o2 = (SDG_field__c)result.data[0];
        system.assertNotEquals('sortablegrid__APIName__c', o2.sortablegrid__APIName__c, 'Expected changed order');
        system.assertEquals(false, result.isError,'Should not get error with valid sort value');


        //test invalid sort
        req.sortColumn='Account.Name';
        SDGResult result3 = getresult(req);
        //should have an error:
        system.assertEquals(true, result3.isError,'Should get error with invalid sort value');

    }

    static testMethod void TestInvalidSDG()
    {
        //Generate test data: an account and an opportunity:
        String testdatarecordid= sdgTestData.GenerateTestSampleData();

        STring erlid = sdgTestData.GenerateTestSDG();
        String stringfield = sdgTestData.GenerateTestSDGFieldString(erlid);
        String datefield = sdgTestData.GenerateTestSDGFieldDate(erlid);
        String booleanfield = sdgTestData.GenerateTestSDGFieldBoolean(erlid);
        String picklistfield = sdgTestData.GenerateTestSDGFieldPicklist(erlid);

        Test.startTest();

        //Generate a request:
        SDGRequest req = new SDGRequest();
        req.SDGTag = sdgTestData.TestSDGName;
        req.ParentRecordID = testdatarecordid;
        req.pageid=1;
        req.pagesize=5;

        system.debug('request: ' + JSON.serialize(req));
        //Now invoke normal list:
        SDGResult result = getresult(req);
        system.debug('result: ' + JSON.serialize(result));
        system.assertEquals(false, result.isError,'TestInvalidSDG: No error expected with valid SDG');
        system.assertEquals(2, result.filteredrowcount,'TestInvalidSDG: Expected 2 sdgfields as this is a valid SDG');

        //Update SDG:
        Sdg__c sdg = [select id, is_valid__c from sdg__c where id = :erlid limit 1];
        sdg.is_valid__c = false;
        update sdg;
        sdg = [select is_valid__c from sdg__c where id = :erlid limit 1];

        system.debug('set ' + sdg.id + ' to ' + sdg.is_valid__c + ' - should fail now');
        system.debug(JSON.serialize(sdg));
        SDGResult result2 = getResult(req);

        system.assertNotEquals('', result2.ErrorMessage,'Expected error message with is_valid=false');

        system.assertEquals(null, result2.filteredrowcount,'Expected rowcount=0 as this is now invalid sdg');
        system.assertEquals(true, result2.isError,'Expected error with is_valid=false');

        Test.stopTest();
    }
    */
}