objects/SDG__c.object
<CustomObject>
    <fields>
        <fullName>All_Rows__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Retrieve all rows - including archived and deleted records. Generally leave as false unless there&apos;s a specific need.</inlineHelpText>
        <label>All Rows</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Sort__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Provides automatic sorting for the grid.  example: Name Asc</inlineHelpText>
        <label>Default Sort</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DisableSharing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disable Sharing rules (ie run &apos;Without Sharing&apos;)</inlineHelpText>
        <label>Disable Sharing Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Filter__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Define SOQL filter here - no AND or WHERE necessary - this will always be applied</inlineHelpText>
        <label>Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Field_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Link to parent record if required.  To show Contacts for an Account - this value should be AccountId as that is the field on Contact that references the Account</inlineHelpText>
        <label>Parent Field Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>API Name of the core sObject to be rendering: eg Contact or CustomObject__c</inlineHelpText>
        <label>sObjectName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sortable Data Grid</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SDG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SDG_Action__c.object
<CustomObject>
    <fields>
        <fullName>Action_Order__c</fullName>
        <label>Action Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Action_Type__c</fullName>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Row</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Row Button</fullName>
                </value>
                <value>
                    <fullName>List Button</fullName>
                </value>
                <value>
                    <fullName>List Multi</fullName>
                    <label>List Multi-Select</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Payload__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Payload for the event.  For LIST actions, will automatically replace #parentrecordId# with valid id.  For ROW actions, will automatically replace fieldnames with # at beginning and end with the corresponding values.  example: 
{
   &quot;recordId&quot;: &quot;#Id#&quot;
}</inlineHelpText>
        <label>Event Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Lightning event to raise: eg c.force:editRecord</inlineHelpText>
        <label>Event</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Icon name from Lightning Design System - eg standard:contact</inlineHelpText>
        <label>Icon</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDG__c</fullName>
        <label>SDG</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipLabel>Sortable Data Grid Actions</relationshipLabel>
        <relationshipName>SDG_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Action</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SDG_Field__c.object
<CustomObject>
    <fields>
        <fullName>APIName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>APIName of the field to render - use dot notation for lookups to other objects: eg Account.Name</inlineHelpText>
        <label>APIName</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldOrder__c</fullName>
        <label>FieldOrder</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field_Style__c</fullName>
        <inlineHelpText>Use a custom renderer with special behaviours</inlineHelpText>
        <label>Custom Renderer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Age</fullName>
                </value>
                <value>
                    <fullName>Summarize:Total</fullName>
                </value>
                <value>
                    <fullName>Summarize:Min</fullName>
                </value>
                <value>
                    <fullName>Summarize:Max</fullName>
                </value>
                <value>
                    <fullName>Summarize:Average</fullName>
                </value>
                <value>
                    <fullName>CTI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hide_Filter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Filter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Label__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Only put a value here if you want to override the default field label (useful when the field is on another object from the core object - eg createdby.name</inlineHelpText>
        <label>Override Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_valid_field__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Enable/Disable field display.  If the package thinks there&apos;s something wrong with the config it will automatically set this value to false.</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sdg__c</fullName>
        <label>sdg</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipName>SDGFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Field</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/sdgMapper.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public class sdgMapper {
    public static SDGAction MapAction(sdg_action__c action)
    {
        SDGAction newAction = new SDGAction();
        newAction.Id = action.Id;
        newAction.label = action.name;
        newAction.event = action.event__c;
        try
        {
            newAction.actionOrder = integer.valueOf( action.action_order__c);
        }
        catch (exception ex)
        {
            newAction.actionOrder = 1;
        }
        
        newAction.Type = action.Action_Type__c;
        newAction.Payload = action.Event_Payload__c;
        newAction.Icon = action.Icon__c;
        return newAction;
    }
    public static SDGField MapField(Schema.DescribeFieldResult dr, String Path, String PathID, Boolean HideFilter, String OverrideLabel, String FieldStyle, Decimal fieldOrder)
    {
        
        SDGField newfield = new SDGField();
        newfield.Id = PathID;
        newfield.ColumnName = Path;
        newfield.FieldStyle = FieldStyle;
        try{
            newfield.FieldOrder = Integer.valueOf(fieldOrder);
        }
        catch(Exception ex)
        {
            newfield.FieldOrder = 1;
        }
        //handle scenario of invalid case
        newfield.ColumnName = path.removeEndIgnoreCase(dr.getName()) + dr.getName();
        
        newfield.fieldType= String.valueof(dr.getType());
        
        newfield.isHTMLFormatted = dr.isHtmlFormatted();
        newfield.canSort = dr.isSortable();
        newfield.canFilter = dr.isFilterable();
        if (HideFilter)
        {
            newfield.canFilter = false;
        }
        
        if (String.isBlank(OverrideLabel))
        {
            newfield.Label =dr.getLabel();
        }
        else
        {
            newfield.label = OverrideLabel;
        }
        
        if (newfield.fieldType ==String.valueOf(Schema.DisplayType.PICKLIST))
        {
            List<AuraSelectOption> options =getPicklistFieldOptions( dr);
            newfield.options = options;
        }
        if (string.isBlank(newfield.fieldType))
        {
            newfield = null;
        }
        return newfield;
    }
    
    public static List<AuraSelectOption>  getPicklistFieldOptions(Schema.DescribeFieldResult dr)
    {
        
        List<Schema.PicklistEntry> ple = dr.getPicklistValues();
        List<AuraSelectOption> options = new List<AuraSelectOption>();
        options.add(new AuraSelectOption('',''));
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new AuraSelectOption(f.getLabel(), f.getValue()));
        }
        
        return options;
    }
    
    public static List<SDGAction> MapToSDGActions(String sObjectName, List<sdg_action__c> actions)
    {
        List<SDGAction> results = new List<SDGAction>();
        List<sdg_action__c> permittedactions  = sdgSecurity.PermittedActions(sObjectName, actions);
        for (SDG_Action__c action : permittedactions)
        {
            
            results.add(MapAction(action));
            
        } 
        return results;
        
    }
    public static List<SDGField> MapToSDGFields(Schema.SObjectType targetType,  List<SDG_Field__c> fields, Boolean updateInvalidFields)
    {
        List<SDGField> newFields = new List<SDGField>();
        
        Boolean needsupdate = false;
        
        for (SDG_Field__c field : fields)
        {
            
            try
            {
                sdgPathParser pp = new SDGPathParser(field.APIName__c, targetType);
                Schema.DescribeFieldResult dr = pp.getDescribe();
                //Just because it isn't accessible doesn't mean there's a problem - just means we don't return it to the UI
                if (dr.isAccessible())
                {
                    SDGField newfield = sdgMapper.MapField(dr, field.APIName__c, field.Id, field.Hide_Filter__c, field.Override_Label__c , field.Field_Style__c, field.fieldOrder__c);
                    if (newfield!=null)
                    {
                        newfield.Scale = dr.getScale();
                        newfields.add(newfield);
                    }
                }
            }
            catch (exception ex)
            {
                //Something bad with getting the field  - probably an invalid path - so for the time being mark the field as invalid so we don't hit this again
                if (updateInvalidFields)
                {
                    field.is_valid_field__c= false;
                    needsupdate = true;
                }
            }
            
        }
        //At least 1 field was invalid, so update db:
        if (needsupdate)
        {
            update fields;
        }
        return newfields;
    }
    
    public static SDG Convert(SDG__c core, List<SDG_Field__c> fields, List<sdg_action__c> actions, Boolean updateInvalidFields)
    {
        SDG CoreSDG = new SDG(core.sObjectName__c, core.Parent_Field_Name__c,  core.sobjectname__c,  core.Filter__c,  core.Default_Sort__c, core.Id, core.All_Rows__c );
        CoreSDG.internalData.DisableSharing = core.DisableSharing__c;
        Schema.SObjectType targetType = Schema.getGlobalDescribe().get(CoreSDG.sObjectName);
        
        
        coreSDG.SDGFields = MapToSDGFields(targetType, fields, updateInvalidFields);
        coreSDG.SDGActions = MapToSDGActions(core.sObjectName__c, actions);
        
        
        return CoreSDG;
        
    }
}