objects/SDG__c.object
<CustomObject>
    <fields>
        <fullName>All_Rows__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Retrieve all rows - including archived and deleted records. Generally leave as false unless there&apos;s a specific need.</inlineHelpText>
        <label>All Rows</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Sort__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Provides automatic sorting for the grid.  example: Name Asc</inlineHelpText>
        <label>Default Sort</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DisableSharing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Disable Sharing rules (ie run &apos;Without Sharing&apos;)</inlineHelpText>
        <label>Disable Sharing Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Filter__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Define SOQL filter here - no AND or WHERE necessary - this will always be applied</inlineHelpText>
        <label>Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Valid__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Whether to enable/disable the grid.</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Field_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Link to parent record if required.  To show Contacts for an Account - this value should be AccountId as that is the field on Contact that references the Account</inlineHelpText>
        <label>Parent Field Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDG_Tag__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique name for the grid</inlineHelpText>
        <label>SDG Tag</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>API Name of the core sObject to be rendering: eg Contact or CustomObject__c</inlineHelpText>
        <label>sObjectName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sortable Data Grid</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SDG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SDG_Action__c.object
<CustomObject>
    <fields>
        <fullName>Action_Order__c</fullName>
        <label>Action Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Action_Type__c</fullName>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Row</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Row Button</fullName>
                </value>
                <value>
                    <fullName>List Button</fullName>
                </value>
                <value>
                    <fullName>List Multi</fullName>
                    <label>List Multi-Select</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Payload__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Payload for the event.  For LIST actions, will automatically replace #parentrecordId# with valid id.  For ROW actions, will automatically replace fieldnames with # at beginning and end with the corresponding values.  example: 
{
   &quot;recordId&quot;: &quot;#Id#&quot;
}</inlineHelpText>
        <label>Event Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Lightning event to raise: eg c.force:editRecord</inlineHelpText>
        <label>Event</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Icon name from Lightning Design System - eg standard:contact</inlineHelpText>
        <label>Icon</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_Createable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only show this action if the user is required to have Create rights on the sObject on the grid.</inlineHelpText>
        <label>Requires Createable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requires_Deletable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only show this action if the user is required to have Delete rights on the sObject on the grid.</inlineHelpText>
        <label>Requires Deletable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requires_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only show this action if the user is required to have Edit rights on the sObject on the grid.</inlineHelpText>
        <label>Requires Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SDG__c</fullName>
        <label>SDG</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipLabel>Sortable Data Grid Actions</relationshipLabel>
        <relationshipName>SDG_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Action</label>
    <language>en_US</language>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SDG_Field__c.object
<CustomObject>
    <fields>
        <fullName>APIName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>APIName of the field to render - use dot notation for lookups to other objects: eg Account.Name</inlineHelpText>
        <label>APIName</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldOrder__c</fullName>
        <label>FieldOrder</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field_Style__c</fullName>
        <inlineHelpText>Use a custom renderer with special behaviours</inlineHelpText>
        <label>Custom Renderer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Age</fullName>
                </value>
                <value>
                    <fullName>Summarize:Total</fullName>
                </value>
                <value>
                    <fullName>Summarize:Min</fullName>
                </value>
                <value>
                    <fullName>Summarize:Max</fullName>
                </value>
                <value>
                    <fullName>Summarize:Average</fullName>
                </value>
                <value>
                    <fullName>CTI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hide_Filter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Filter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Label__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Only put a value here if you want to override the default field label (useful when the field is on another object from the core object - eg createdby.name</inlineHelpText>
        <label>Override Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_valid_field__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Enable/Disable field display.  If the package thinks there&apos;s something wrong with the config it will automatically set this value to false.</inlineHelpText>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sdg__c</fullName>
        <label>sdg</label>
        <referenceTo>SDG__c</referenceTo>
        <relationshipName>SDGFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sortable Data Grid Field</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sortable Data Grid Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/sdgDataProviderNative.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
global with sharing class sdgDataProviderNative implements sdgIDataProvider {
    global static Boolean isUserSelectable()
    {
        return false;
    }
    global static SDGResult getData(SDG CoreSDG, SDGRequest request)
    {
        
        SDGResult result =  sdgQueryEngine.getSDGResultRaw(CoreSDG, request);
        return result;
    }
    
    global   SDG LoadSDG(String SDGTag, String ParentRecordId)
    {
        SDG CoreSDG = null;
        
        sdgSecurity.CanQuery('sdgDataProviderNative:LoadSDG', 'SDG__c', 'sobjectname__c, parent_field_name__c, filter__c, default_sort__c, is_valid__c, All_Rows__c, DisableSharing__c', 'Id', sdgNamespaceUtility.GetNamespace(), true);
        sdgSecurity.CanQuery('sdgDataProviderNative:GetSDGActions' , 'SDG_Action__c', 'event__c, action_order__c, Requires_Createable__c, requires_deletable__c, Requires_Editable__c, Action_Type__c, Event_Payload__c, Icon__c', 'id,name', sdgNamespaceUtility.GetNamespace(), true);
        sdgSecurity.CanQuery('sdgDataProviderNative:GetSDGFields', 'SDG_Field__c', 'apiname__c,  FieldOrder__c, Field_Style__c, Hide_Filter__c, Override_Label__c', 'id,name', sdgNamespaceUtility.GetNamespace(), true);
        
        List<SDG__c> sdgs= [select id, sobjectname__c, parent_field_name__c, filter__c, default_sort__c, is_valid__c, All_Rows__c, DisableSharing__c, (select id, name, event__c, Requires_Createable__c, Requires_Editable__c, requires_deletable__c, Action_Type__c, Event_Payload__c, Icon__c, action_order__c  from sdg_actions__r), (select id, name, apiname__c,  FieldOrder__c, Field_Style__c, Hide_Filter__c, Override_Label__c  from SDGFields__r where is_valid_field__c =true) from SDG__c where SDG_Tag__c = :SDGTag ];
        if (sdgs.size()!=1)
        {
            throw new SDGException('sdgDataProviderNative:LoadSDG: Invalid number of SDG results for name: ' + SDGTag + '. retrieved: ' + sdgs.size());
        }
        else
        {
            //Now we can load this:
            SDG__c e;
            e = sdgs[0];
            
            system.debug('sdgDataProviderNative:LoadSDG:Validity: ' + e.is_valid__c);
            if (!e.is_valid__c)
            {
                system.debug('This is an invalid SDG');
                throw new SDGException('SDG: ' + SDGTag + ' is marked as invalid');
            }
            
            CoreSDG = new SDG(e.sObjectName__c, e.Parent_Field_Name__c,  e.sobjectname__c,  e.Filter__c,  e.Default_Sort__c, e.Id, e.All_Rows__c );
            CoreSDG.internalData.DisableSharing = e.DisableSharing__c;

            Schema.SObjectType targetType = Schema.getGlobalDescribe().get(CoreSDG.sObjectName);
            if (targetType==null)
            {
                system.debug('sdgDataProviderNative:LoadSDG: invalid sObjectName');
                throw new SDGException('sdgDataProviderNative: Invalid sObjectName provided - are you missing a namespace?');
            }
            Id CoreSDGId = CoreSDG.InternalData.sUniqueKey;

            List<SDG_Field__c> fields = e.sdgfields__r;
            if (fields!=null)
                CoreSDG.SDGFields = GetSDGFields(fields, targetType);
          
            List<SDG_Action__c> actions = e.sdg_actions__r;
            if (actions!=null)
                CoreSDG.SDGActions = GetSDGActions(actions, e.sObjectName__c);
        }
        return coreSDG;
    }
    
    private  List<SDGAction> GetSDGActions(List<SDG_Action__c> actions, String sObjectName)
    {
        

        List<SDGAction> results = sdgMapper.MapToSDGActions(sObjectName, actions);
        results.sort();
        return results;
    }
    private  List<SDGField> GetSDGFields(List<sdg_field__c> fields, Schema.SObjectType targetType )
    {
        
        if (fields.size()==0)
        {
            throw new SDGException('sdgDataProviderNative:GetSDGFields: SDG has no fields');
        }
        
        //Now convert to fields - do FLS checks as well
        List<SDGField> results = sdgMapper.MapToSDGFields(targetType, fields, true);
        results.sort();
        return results;
        
    }

    
}